---
name: Test Flyway versions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flyway:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flyway-version: [ 7.15.0, 8.2.3, 8.5.13, 9.22.3 ] # oldest supported, first 8.x that supports H2, latest 8.x.x, latest 9.x.x

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build code
        id: install_fast
        env:
          MAVEN_CONFIG: "-B -ff"
        run: |
          ./mvnw --version
          make install-fast

      - name: run tests
        id: run_tests
        env:
          MAVEN_CONFIG: "-B -ff -pl :jdbi3-testing -Ddep.flyway.version=${{ matrix.flyway-version }}"
        run: |
          ./mvnw --version
          make run-tests

      - uses: actions/upload-artifact@v4
        name: upload build logs
        id: upload_build_logs
        if: ${{ always() }}
        with:
          name: build logs (${{ github.job }}, ${{ matrix.flyway-version }})
          retention-days: 90
          path: |
            **/target
            !**/target/**/*.jar
            !**/target/**/*.class

      - uses: actions/upload-artifact@v4
        name: upload build artifacts
        id: upload_build_artifacts
        with:
          name: build artifacts (${{ github.job }}, ${{ matrix.flyway-version }})
          retention-days: 1
          path: |
            **/target/**/*.jar
