---
name: Test Postgres versions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres-version: [ 9.6, 10, 11, 12, 13, 14, 15 ]

    steps:
      - uses: actions/checkout@v3

      - name: Install locales on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y locales-all

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: test postgres versions
        env:
          MAVEN_CONFIG: "-e -B -fae -Dpg-embedded.postgres-version=${{ matrix.postgres-version }}"
        run: |
          make install
